# Change variables in this file to reflect your needs, wishes, constraints
MKDIR = mkdir -p
ECHO = echo
RM = rm -f
INSTALL = install

prefix		?=/usr/local
exec_prefix	?=${prefix}
datarootdir     ?=${prefix}/share
datadir         ?=${datarootdir}
BINDIR		?="$(DESTDIR)${exec_prefix}/bin"
LIBDIR		?="$(DESTDIR)${exec_prefix}/lib"
DATADIR		?="$(DESTDIR)${prefix}/share"
MANDIR		?="$(DESTDIR)${datarootdir}/man"

YACC            = bison -y
YFLAGS		?=  -d
LEX		?=  flex
LFLAGS		?=  

DOXYGEN         ?=  error
MAKE            ?=  make

PROOF_PRODUCTION ?=  

CPPFLAGS        =  -DPROOF -DHAVE___BUILTIN_EXPECT
CFLAGS          =  -Wall -finline-limit=1000000 -Wno-unused-function -O3 -DNDEBUG -fomit-frame-pointer
LDFLAGS         =  -lm -lgmp

ETAGS		= etags
CTAGS		= ctags

ECHO_N		= printf
ECHO		= echo

# Installation directories
PREFIX      = $(prefix)
PREFIX_BIN  = $(prefix)/bin

CC = gcc

%.o:%.c
	@$(ECHO) "CC $<"
	@$(CC) $(INCLUDES) $(CPPFLAGS) $(CFLAGS) -o $@ -c $<

%.c:%.y
	@echo $(YACC) $(YFLAGS) -o $@  $<
	@$(ECHO) "YACC $<"
	@$(YACC) $(YFLAGS) -o $@  $<

%.c:%.l
	@echo $(LEX) $(LFLAGS) -o $@ $<
	@$(ECHO) "LEX $<"
	@$(LEX) $(LFLAGS) -o $@ $<

clean::
	@$(RM) *~ *.o *.da *.bb *.bbg dependencies smtsyn.output

veryclean:: clean
	@$(ECHO) "Cleanup generated configuration and build files..."
	@$(RM) -Rf config.log config.status configure Makefile Makefile.config autom4te.cache
